-- =====================================================================
-- COMPLETE SCHEMA SETUP  —  paste-once install for the Supabase SQL Editor
--
-- This is every migration in supabase/migrations/, concatenated in order.
-- It exists so the system can be installed entirely from the web dashboard,
-- with no terminal and no Supabase CLI.
--
-- HOW TO USE
--   1. Supabase Dashboard -> SQL Editor -> New query
--   2. Paste this whole file
--   3. Run
--   4. Expect "Success. No rows returned"
--
-- Safe to run more than once. Every statement is idempotent, so if it fails
-- partway you can fix the cause and run the whole file again.
--
-- DO NOT EDIT THIS FILE. It is generated from the migrations by
-- scripts/build-setup-sql.mjs. Edit a migration, then regenerate.
-- =====================================================================



-- #####################################################################
-- # BEGIN 20260101000100_core_schema.sql
-- #####################################################################

-- =====================================================================
-- Local Government Agenda & Minutes Management System
-- 0100 - Core schema: enums, tables, constraints, indexes
-- =====================================================================

create extension if not exists "pgcrypto";
create extension if not exists "pg_trgm";

-- ---------------------------------------------------------------------
-- Enumerated types
-- ---------------------------------------------------------------------
do $$ begin
  create type public.app_role as enum ('super_admin', 'admin', 'editor', 'read_only');
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.meeting_status as enum ('draft', 'published', 'archived');
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.minutes_status as enum ('not_available', 'draft', 'pending_approval', 'approved');
exception when duplicate_object then null; end $$;

-- ---------------------------------------------------------------------
-- municipalities (tenants)
-- ---------------------------------------------------------------------
create table if not exists public.municipalities (
  id              uuid primary key default gen_random_uuid(),
  name            text not null check (length(btrim(name)) between 1 and 200),
  slug            text not null unique check (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
  timezone        text not null default 'America/Chicago',
  logo_url        text,
  website_url     text,
  contact_email   text,
  contact_phone   text,
  contact_address text,
  -- Public/branding configuration. Shape is validated in the application layer
  -- (lib/validation/schemas.ts -> municipalityConfigurationSchema).
  configuration   jsonb not null default '{}'::jsonb,
  active          boolean not null default true,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

comment on column public.municipalities.timezone is
  'IANA time zone used for every meeting date/time calculation for this tenant.';

-- ---------------------------------------------------------------------
-- profiles (application users, 1:1 with auth.users)
-- ---------------------------------------------------------------------
create table if not exists public.profiles (
  id               uuid primary key default gen_random_uuid(),
  auth_user_id     uuid not null unique references auth.users (id) on delete cascade,
  municipality_id  uuid references public.municipalities (id) on delete restrict,
  display_name     text not null check (length(btrim(display_name)) between 1 and 200),
  email            text not null check (email ~* '^[^@\s]+@[^@\s]+\.[^@\s]+$'),
  role             public.app_role not null default 'read_only',
  active           boolean not null default true,
  disabled_at      timestamptz,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now(),
  -- Only platform super administrators may exist outside a municipality.
  constraint profiles_tenant_required
    check (role = 'super_admin' or municipality_id is not null)
);

create unique index if not exists profiles_municipality_email_key
  on public.profiles (municipality_id, lower(email));
create index if not exists profiles_municipality_idx
  on public.profiles (municipality_id) where active;

-- ---------------------------------------------------------------------
-- role_permissions (single source of truth for RBAC)
--   Mirrored in TypeScript at lib/permissions/permissions.ts.
--   tests/permissions.parity.test.ts asserts the two never drift.
-- ---------------------------------------------------------------------
create table if not exists public.role_permissions (
  role       public.app_role not null,
  permission text not null check (permission ~ '^[a-z_]+\.[a-z_]+$'),
  primary key (role, permission)
);

-- ---------------------------------------------------------------------
-- document_types (extensible: packets, ordinances, notices ... later)
-- ---------------------------------------------------------------------
create table if not exists public.document_types (
  code          text primary key check (code ~ '^[a-z][a-z0-9_]*$'),
  label         text not null,
  display_order integer not null default 0,
  active        boolean not null default true,
  created_at    timestamptz not null default now()
);

-- ---------------------------------------------------------------------
-- meeting_categories
-- ---------------------------------------------------------------------
create table if not exists public.meeting_categories (
  id              uuid primary key default gen_random_uuid(),
  municipality_id uuid not null references public.municipalities (id) on delete cascade,
  name            text not null check (length(btrim(name)) between 1 and 120),
  slug            text not null check (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
  description     text,
  display_order   integer not null default 0,
  active          boolean not null default true,
  archived_at     timestamptz,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now(),
  unique (municipality_id, slug)
);

create index if not exists meeting_categories_tenant_order_idx
  on public.meeting_categories (municipality_id, display_order, name);

-- ---------------------------------------------------------------------
-- meetings (the primary record)
-- ---------------------------------------------------------------------
create table if not exists public.meetings (
  id              uuid primary key default gen_random_uuid(),
  municipality_id uuid not null references public.municipalities (id) on delete cascade,
  category_id     uuid not null references public.meeting_categories (id) on delete restrict,
  title           text not null check (length(btrim(title)) between 1 and 300),
  slug            text not null check (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
  description     text,
  meeting_date    date not null,
  meeting_time    time,
  location        text,
  status          public.meeting_status  not null default 'draft',
  minutes_status  public.minutes_status  not null default 'not_available',
  -- Absolute instant, derived from meeting_date/meeting_time in the tenant's
  -- time zone. Maintained by trigger; never written by the application.
  starts_at       timestamptz not null,
  published_at    timestamptz,
  archived_at     timestamptz,
  created_by      uuid references public.profiles (id) on delete set null,
  updated_by      uuid references public.profiles (id) on delete set null,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now(),
  search_vector   tsvector generated always as (
      setweight(to_tsvector('english', coalesce(title, '')), 'A') ||
      setweight(to_tsvector('english', coalesce(description, '')), 'B') ||
      setweight(to_tsvector('english', coalesce(location, '')), 'C')
    ) stored,
  unique (municipality_id, meeting_date, slug)
);

create index if not exists meetings_public_listing_idx
  on public.meetings (municipality_id, status, starts_at desc);
create index if not exists meetings_upcoming_idx
  on public.meetings (municipality_id, starts_at)
  where status = 'published';
create index if not exists meetings_category_idx
  on public.meetings (municipality_id, category_id, starts_at desc);
create index if not exists meetings_search_idx
  on public.meetings using gin (search_vector);
create index if not exists meetings_title_trgm_idx
  on public.meetings using gin (title gin_trgm_ops);
create index if not exists meetings_updated_idx
  on public.meetings (municipality_id, updated_at desc);

-- ---------------------------------------------------------------------
-- meeting_documents (versioned child records)
-- ---------------------------------------------------------------------
create table if not exists public.meeting_documents (
  id                uuid primary key default gen_random_uuid(),
  municipality_id   uuid not null references public.municipalities (id) on delete cascade,
  meeting_id        uuid not null references public.meetings (id) on delete cascade,
  document_type     text not null references public.document_types (code) on delete restrict,
  posted_date       date not null,
  storage_path      text not null unique,
  -- Stable, human-readable identifier used to build the permanent public URL.
  -- Preserved across replacements so shared links never break.
  public_slug       text not null check (public_slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
  original_filename text not null,
  stored_filename   text not null,
  mime_type         text not null default 'application/pdf'
                      check (mime_type = 'application/pdf'),
  file_size         bigint not null check (file_size > 0),
  sha256            text check (sha256 is null or sha256 ~ '^[a-f0-9]{64}$'),
  version           integer not null default 1 check (version >= 1),
  active_version    boolean not null default true,
  uploaded_by       uuid references public.profiles (id) on delete set null,
  created_at        timestamptz not null default now(),
  replaced_at       timestamptz,
  removed_at        timestamptz,
  unique (meeting_id, document_type, version)
);

-- Exactly one live document per meeting + type.
create unique index if not exists meeting_documents_active_key
  on public.meeting_documents (meeting_id, document_type)
  where active_version;

-- The permanent public URL must resolve to exactly one live document.
create unique index if not exists meeting_documents_public_slug_key
  on public.meeting_documents (municipality_id, public_slug)
  where active_version;

create index if not exists meeting_documents_meeting_idx
  on public.meeting_documents (meeting_id, document_type, version desc);
create index if not exists meeting_documents_recent_idx
  on public.meeting_documents (municipality_id, created_at desc);

-- ---------------------------------------------------------------------
-- audit_log (append only; see 0300_audit.sql for the write triggers)
-- ---------------------------------------------------------------------
create table if not exists public.audit_log (
  id              bigserial primary key,
  municipality_id uuid references public.municipalities (id) on delete set null,
  user_id         uuid references public.profiles (id) on delete set null,
  user_name       text,
  user_email      text,
  action          text not null,
  entity_type     text not null,
  entity_id       text,
  previous_data   jsonb,
  new_data        jsonb,
  metadata        jsonb not null default '{}'::jsonb,
  ip_address      inet,
  user_agent      text,
  created_at      timestamptz not null default now()
);

create index if not exists audit_log_tenant_time_idx
  on public.audit_log (municipality_id, created_at desc);
create index if not exists audit_log_entity_idx
  on public.audit_log (entity_type, entity_id, created_at desc);
create index if not exists audit_log_action_idx
  on public.audit_log (municipality_id, action, created_at desc);

-- # END 20260101000100_core_schema.sql

-- #####################################################################
-- # BEGIN 20260101000200_functions_triggers.sql
-- #####################################################################

-- =====================================================================
-- 0200 - Functions and triggers
-- =====================================================================

-- ---------------------------------------------------------------------
-- Identity helpers used by every RLS policy.
-- SECURITY DEFINER so a policy on profiles can look at profiles without
-- recursing through its own policy.
-- ---------------------------------------------------------------------
create or replace function public.current_profile()
returns public.profiles
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select p.* from public.profiles p
  where p.auth_user_id = auth.uid() and p.active
  limit 1;
$$;

create or replace function public.current_role_name()
returns public.app_role
language sql stable security definer set search_path = public, pg_temp
as $$ select (public.current_profile()).role; $$;

create or replace function public.current_municipality_id()
returns uuid
language sql stable security definer set search_path = public, pg_temp
as $$ select (public.current_profile()).municipality_id; $$;

create or replace function public.is_super_admin()
returns boolean
language sql stable security definer set search_path = public, pg_temp
as $$ select coalesce(public.current_role_name() = 'super_admin', false); $$;

-- Does the signed-in user hold `perm`? Super administrators hold everything.
create or replace function public.has_permission(perm text)
returns boolean
language sql stable security definer set search_path = public, pg_temp
as $$
  select case
    when auth.uid() is null then false
    when public.is_super_admin() then true
    else exists (
      select 1 from public.role_permissions rp
      where rp.role = public.current_role_name()
        and rp.permission = perm
    )
  end;
$$;

-- Tenant gate: a user may only touch rows inside their own municipality.
create or replace function public.can_access_municipality(target uuid)
returns boolean
language sql stable security definer set search_path = public, pg_temp
as $$
  select public.is_super_admin()
      or (target is not null and target = public.current_municipality_id());
$$;

-- Combined helper: permission AND tenant match.
create or replace function public.may(perm text, target uuid)
returns boolean
language sql stable security definer set search_path = public, pg_temp
as $$ select public.has_permission(perm) and public.can_access_municipality(target); $$;

-- ---------------------------------------------------------------------
-- Generic bookkeeping
-- ---------------------------------------------------------------------
create or replace function public.touch_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists municipalities_touch on public.municipalities;
create trigger municipalities_touch before update on public.municipalities
  for each row execute function public.touch_updated_at();
drop trigger if exists profiles_touch on public.profiles;
create trigger profiles_touch before update on public.profiles
  for each row execute function public.touch_updated_at();
drop trigger if exists meeting_categories_touch on public.meeting_categories;
create trigger meeting_categories_touch before update on public.meeting_categories
  for each row execute function public.touch_updated_at();
drop trigger if exists meetings_touch on public.meetings;
create trigger meetings_touch before update on public.meetings
  for each row execute function public.touch_updated_at();

-- ---------------------------------------------------------------------
-- Time zone integrity
-- ---------------------------------------------------------------------
create or replace function public.assert_valid_timezone()
returns trigger language plpgsql as $$
begin
  if not exists (select 1 from pg_timezone_names where name = new.timezone) then
    raise exception 'Unknown IANA time zone: %', new.timezone
      using errcode = '22023';
  end if;
  return new;
end;
$$;

drop trigger if exists municipalities_timezone_check on public.municipalities;
create trigger municipalities_timezone_check
  before insert or update of timezone on public.municipalities
  for each row execute function public.assert_valid_timezone();

-- starts_at is the single source of truth for "is this meeting upcoming or
-- past". It is computed in the municipality's own time zone, never the
-- visitor's browser time zone.
create or replace function public.set_meeting_starts_at()
returns trigger language plpgsql
set search_path = public, pg_temp
as $$
declare tz text;
begin
  select m.timezone into tz from public.municipalities m where m.id = new.municipality_id;
  if tz is null then
    raise exception 'Municipality % not found', new.municipality_id using errcode = '23503';
  end if;
  new.starts_at := (new.meeting_date + coalesce(new.meeting_time, time '00:00')) at time zone tz;
  return new;
end;
$$;

drop trigger if exists meetings_set_starts_at on public.meetings;
create trigger meetings_set_starts_at
  before insert or update of meeting_date, meeting_time, municipality_id on public.meetings
  for each row execute function public.set_meeting_starts_at();

-- If a city changes its configured time zone, every stored instant is recomputed.
create or replace function public.recompute_tenant_meeting_instants()
returns trigger language plpgsql
set search_path = public, pg_temp
as $$
begin
  if new.timezone is distinct from old.timezone then
    update public.meetings
       set starts_at = (meeting_date + coalesce(meeting_time, time '00:00')) at time zone new.timezone
     where municipality_id = new.id;
  end if;
  return new;
end;
$$;

drop trigger if exists municipalities_timezone_recompute on public.municipalities;
create trigger municipalities_timezone_recompute
  after update of timezone on public.municipalities
  for each row execute function public.recompute_tenant_meeting_instants();

-- ---------------------------------------------------------------------
-- Meeting lifecycle bookkeeping
-- ---------------------------------------------------------------------
create or replace function public.maintain_meeting_lifecycle()
returns trigger language plpgsql as $$
begin
  if tg_op = 'INSERT' then
    if new.status = 'published' then new.published_at := coalesce(new.published_at, now()); end if;
    if new.status = 'archived'  then new.archived_at  := coalesce(new.archived_at, now());  end if;
    return new;
  end if;

  if new.status is distinct from old.status then
    if new.status = 'published' then
      new.published_at := coalesce(new.published_at, now());
      new.archived_at  := null;
    elsif new.status = 'archived' then
      new.archived_at := now();
    elsif new.status = 'draft' then
      new.published_at := null;
      new.archived_at  := null;
    end if;
  end if;
  return new;
end;
$$;

drop trigger if exists meetings_lifecycle on public.meetings;
create trigger meetings_lifecycle
  before insert or update on public.meetings
  for each row execute function public.maintain_meeting_lifecycle();

-- The category a meeting points at must belong to the same municipality.
create or replace function public.assert_category_tenant()
returns trigger language plpgsql
set search_path = public, pg_temp
as $$
declare owner uuid;
begin
  select municipality_id into owner from public.meeting_categories where id = new.category_id;
  if owner is null or owner <> new.municipality_id then
    raise exception 'Category does not belong to this municipality'
      using errcode = '23514';
  end if;
  return new;
end;
$$;

drop trigger if exists meetings_category_tenant on public.meetings;
create trigger meetings_category_tenant
  before insert or update of category_id, municipality_id on public.meetings
  for each row execute function public.assert_category_tenant();

-- A document must live under the same tenant and meeting.
create or replace function public.assert_document_tenant()
returns trigger language plpgsql
set search_path = public, pg_temp
as $$
declare owner uuid;
begin
  select municipality_id into owner from public.meetings where id = new.meeting_id;
  if owner is null or owner <> new.municipality_id then
    raise exception 'Document does not belong to the meeting''s municipality'
      using errcode = '23514';
  end if;
  return new;
end;
$$;

drop trigger if exists meeting_documents_tenant on public.meeting_documents;
create trigger meeting_documents_tenant
  before insert or update of meeting_id, municipality_id on public.meeting_documents
  for each row execute function public.assert_document_tenant();

-- Uploading minutes moves a meeting off "Not Available" exactly once, so a
-- clerk never has to remember to change two fields.
create or replace function public.sync_minutes_status_on_upload()
returns trigger language plpgsql
set search_path = public, pg_temp
as $$
begin
  if new.document_type = 'minutes' and new.active_version then
    update public.meetings
       set minutes_status = 'draft'
     where id = new.meeting_id and minutes_status = 'not_available';
  end if;
  return new;
end;
$$;

drop trigger if exists meeting_documents_minutes_status on public.meeting_documents;
create trigger meeting_documents_minutes_status
  after insert on public.meeting_documents
  for each row execute function public.sync_minutes_status_on_upload();

-- ---------------------------------------------------------------------
-- Public visibility rules, in one place, used by RLS and by the API.
-- ---------------------------------------------------------------------
-- Minutes are public only once the governing body has approved them, unless
-- the municipality has opted in to publishing pending minutes.
create or replace function public.minutes_publicly_visible(
  m_status public.minutes_status,
  config jsonb
) returns boolean
language sql immutable as $$
  select m_status = 'approved'
      or (m_status = 'pending_approval'
          and coalesce((config ->> 'publish_pending_minutes')::boolean, false));
$$;

create or replace function public.document_publicly_visible(doc_id uuid)
returns boolean
language sql stable security definer set search_path = public, pg_temp
as $$
  select coalesce(bool_or(
      d.active_version
      and d.removed_at is null
      and m.status in ('published', 'archived')
      and (d.document_type <> 'minutes'
           or public.minutes_publicly_visible(m.minutes_status, mu.configuration))
    ), false)
  from public.meeting_documents d
  join public.meetings m on m.id = d.meeting_id
  join public.municipalities mu on mu.id = d.municipality_id
  where d.id = doc_id;
$$;

-- # END 20260101000200_functions_triggers.sql

-- #####################################################################
-- # BEGIN 20260101000300_audit.sql
-- #####################################################################

-- =====================================================================
-- 0300 - Audit trail
-- Every write to an audited table produces audit rows from inside the
-- database, so an event cannot be skipped by forgetting to call a helper.
-- =====================================================================

-- Request context, when the write arrived through PostgREST.
create or replace function public.request_ip()
returns inet language plpgsql stable as $$
declare raw text;
begin
  raw := split_part(
    coalesce(current_setting('request.headers', true)::json ->> 'x-forwarded-for', ''), ',', 1);
  if btrim(raw) = '' then return null; end if;
  return btrim(raw)::inet;
exception when others then return null;
end;
$$;

create or replace function public.request_user_agent()
returns text language plpgsql stable as $$
begin
  return left(current_setting('request.headers', true)::json ->> 'user-agent', 512);
exception when others then return null;
end;
$$;

-- Single writer for audit rows. SECURITY DEFINER because `authenticated`
-- has no direct INSERT grant on audit_log.
create or replace function public.record_audit_event(
  p_municipality_id uuid,
  p_action          text,
  p_entity_type     text,
  p_entity_id       text default null,
  p_previous_data   jsonb default null,
  p_new_data        jsonb default null,
  p_metadata        jsonb default '{}'::jsonb
) returns bigint
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  prof public.profiles;
  new_id bigint;
begin
  prof := public.current_profile();
  insert into public.audit_log (
    municipality_id, user_id, user_name, user_email, action, entity_type,
    entity_id, previous_data, new_data, metadata, ip_address, user_agent)
  values (
    coalesce(p_municipality_id, prof.municipality_id), prof.id, prof.display_name,
    prof.email, p_action, p_entity_type, p_entity_id, p_previous_data, p_new_data,
    coalesce(p_metadata, '{}'::jsonb), public.request_ip(), public.request_user_agent())
  returning id into new_id;
  return new_id;
end;
$$;

grant execute on function public.record_audit_event(uuid, text, text, text, jsonb, jsonb, jsonb)
  to authenticated;

-- Columns that are noise in a diff.
create or replace function public.audit_scrub(payload jsonb)
returns jsonb language sql immutable as $$
  select coalesce(payload, '{}'::jsonb) - 'search_vector' - 'updated_at';
$$;

-- ---------------------------------------------------------------------
-- Generic row auditor. Derives semantic action names from the diff so the
-- log reads like a records history rather than a table changelog.
-- ---------------------------------------------------------------------
create or replace function public.audit_row_change()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  entity   text := tg_argv[0];
  tenant   uuid;
  old_j    jsonb := case when tg_op = 'INSERT' then null else public.audit_scrub(to_jsonb(old)) end;
  new_j    jsonb := case when tg_op = 'DELETE' then null else public.audit_scrub(to_jsonb(new)) end;
  actions  text[] := '{}';
  act      text;
  meta     jsonb := '{}'::jsonb;
begin
  tenant := coalesce(
    (new_j ->> 'municipality_id')::uuid,
    (old_j ->> 'municipality_id')::uuid);

  if tg_op = 'INSERT' then
    if entity = 'document' then
      actions := array[ case when new.version > 1 then 'document.replaced'
                             else 'document.uploaded' end ];
      meta := jsonb_build_object('document_type', new.document_type, 'version', new.version);
    else
      actions := array[entity || '.created'];
    end if;

  elsif tg_op = 'DELETE' then
    actions := array[entity || '.deleted'];

  else
    if entity = 'meeting' then
      if new.status is distinct from old.status then
        actions := actions || case new.status
          when 'published' then 'meeting.published'
          when 'archived'  then 'meeting.archived'
          when 'draft'     then case when old.status = 'archived'
                                     then 'meeting.restored'
                                     else 'meeting.unpublished' end
        end;
      end if;
      if new.minutes_status is distinct from old.minutes_status then
        actions := actions || 'meeting.minutes_status_changed';
        meta := meta || jsonb_build_object('from', old.minutes_status, 'to', new.minutes_status);
      end if;
      if new.category_id is distinct from old.category_id then
        actions := actions || 'meeting.category_changed';
      end if;
      if actions = '{}' then actions := array['meeting.updated']; end if;

    elsif entity = 'document' then
      if old.active_version and not new.active_version then
        actions := array['document.superseded'];
      elsif new.removed_at is not null and old.removed_at is null then
        actions := array['document.removed'];
      else
        actions := array['document.updated'];
      end if;
      meta := jsonb_build_object('document_type', new.document_type, 'version', new.version);

    elsif entity = 'user' then
      if new.role is distinct from old.role then
        actions := actions || 'user.role_changed';
        meta := meta || jsonb_build_object('from', old.role, 'to', new.role);
      end if;
      if new.active is distinct from old.active then
        actions := actions || case when new.active then 'user.enabled' else 'user.disabled' end;
      end if;
      if actions = '{}' then actions := array['user.updated']; end if;

    else
      actions := array[entity || '.updated'];
    end if;
  end if;

  foreach act in array actions loop
    perform public.record_audit_event(
      tenant, act, entity,
      coalesce(new_j ->> 'id', old_j ->> 'id'),
      old_j, new_j, meta);
  end loop;

  return null;
end;
$$;

drop trigger if exists meetings_audit on public.meetings;
create trigger meetings_audit
  after insert or update or delete on public.meetings
  for each row execute function public.audit_row_change('meeting');

drop trigger if exists meeting_documents_audit on public.meeting_documents;
create trigger meeting_documents_audit
  after insert or update or delete on public.meeting_documents
  for each row execute function public.audit_row_change('document');

drop trigger if exists meeting_categories_audit on public.meeting_categories;
create trigger meeting_categories_audit
  after insert or update or delete on public.meeting_categories
  for each row execute function public.audit_row_change('category');

drop trigger if exists profiles_audit on public.profiles;
create trigger profiles_audit
  after insert or update or delete on public.profiles
  for each row execute function public.audit_row_change('user');

drop trigger if exists municipalities_audit on public.municipalities;
create trigger municipalities_audit
  after insert or update or delete on public.municipalities
  for each row execute function public.audit_row_change('municipality');

-- ---------------------------------------------------------------------
-- Tamper resistance
-- ---------------------------------------------------------------------
create or replace function public.reject_audit_mutation()
returns trigger language plpgsql as $$
begin
  raise exception 'The audit log is append only'
    using errcode = '42501';
end;
$$;

drop trigger if exists audit_log_immutable on public.audit_log;
create trigger audit_log_immutable
  before update or delete on public.audit_log
  for each row execute function public.reject_audit_mutation();

revoke insert, update, delete on public.audit_log from anon, authenticated;

-- # END 20260101000300_audit.sql

-- #####################################################################
-- # BEGIN 20260101000400_rls_policies.sql
-- #####################################################################

-- =====================================================================
-- 0400 - Row-Level Security
--
-- Every table is deny-by-default. The public (anon) role can read only
-- explicitly published records. Authenticated users are confined to their
-- own municipality by public.can_access_municipality(), and to their own
-- capabilities by public.has_permission().
-- =====================================================================

alter table public.municipalities     enable row level security;
alter table public.profiles           enable row level security;
alter table public.role_permissions   enable row level security;
alter table public.document_types     enable row level security;
alter table public.meeting_categories enable row level security;
alter table public.meetings           enable row level security;
alter table public.meeting_documents  enable row level security;
alter table public.audit_log          enable row level security;

grant usage on schema public to anon, authenticated;
grant select on public.municipalities, public.meeting_categories,
                public.meetings, public.meeting_documents,
                public.document_types, public.role_permissions
  to anon, authenticated;
grant select, insert, update, delete
  on public.meetings, public.meeting_documents, public.meeting_categories,
     public.profiles, public.municipalities
  to authenticated;
grant select on public.audit_log to authenticated;

-- ---------------------------------------------------------------------
-- municipalities
-- ---------------------------------------------------------------------
drop policy if exists municipalities_public_read on public.municipalities;
create policy municipalities_public_read on public.municipalities
  for select to anon using (active);

drop policy if exists municipalities_member_read on public.municipalities;
create policy municipalities_member_read on public.municipalities
  for select to authenticated
  using (public.is_super_admin() or id = public.current_municipality_id());

drop policy if exists municipalities_update on public.municipalities;
create policy municipalities_update on public.municipalities
  for update to authenticated
  using (public.may('municipality.update', id))
  with check (public.may('municipality.update', id));

drop policy if exists municipalities_insert on public.municipalities;
create policy municipalities_insert on public.municipalities
  for insert to authenticated
  with check (public.is_super_admin());

drop policy if exists municipalities_delete on public.municipalities;
create policy municipalities_delete on public.municipalities
  for delete to authenticated
  using (public.is_super_admin());

-- ---------------------------------------------------------------------
-- reference data
-- ---------------------------------------------------------------------
drop policy if exists document_types_read on public.document_types;
create policy document_types_read on public.document_types
  for select to anon, authenticated using (true);

drop policy if exists role_permissions_read on public.role_permissions;
create policy role_permissions_read on public.role_permissions
  for select to authenticated using (true);

-- ---------------------------------------------------------------------
-- profiles
-- ---------------------------------------------------------------------
drop policy if exists profiles_self_read on public.profiles;
create policy profiles_self_read on public.profiles
  for select to authenticated using (auth_user_id = auth.uid());

drop policy if exists profiles_tenant_read on public.profiles;
create policy profiles_tenant_read on public.profiles
  for select to authenticated
  using (public.may('user.read', municipality_id));

drop policy if exists profiles_manage_insert on public.profiles;
create policy profiles_manage_insert on public.profiles
  for insert to authenticated
  with check (
    public.may('user.manage', municipality_id)
    -- Only a super administrator may mint another super administrator.
    and (role <> 'super_admin' or public.is_super_admin())
  );

drop policy if exists profiles_manage_update on public.profiles;
create policy profiles_manage_update on public.profiles
  for update to authenticated
  using (public.may('user.manage', municipality_id))
  with check (
    public.may('user.manage', municipality_id)
    and (role <> 'super_admin' or public.is_super_admin())
  );

-- Accounts are disabled, not deleted, so history keeps its author.
drop policy if exists profiles_delete on public.profiles;
create policy profiles_delete on public.profiles
  for delete to authenticated
  using (public.is_super_admin());

-- ---------------------------------------------------------------------
-- meeting_categories
-- ---------------------------------------------------------------------
drop policy if exists categories_public_read on public.meeting_categories;
create policy categories_public_read on public.meeting_categories
  for select to anon
  using (
    active and archived_at is null
    and exists (select 1 from public.municipalities m
                where m.id = municipality_id and m.active)
  );

drop policy if exists categories_member_read on public.meeting_categories;
create policy categories_member_read on public.meeting_categories
  for select to authenticated
  using (public.may('category.read', municipality_id));

drop policy if exists categories_insert on public.meeting_categories;
create policy categories_insert on public.meeting_categories
  for insert to authenticated
  with check (public.may('category.manage', municipality_id));

drop policy if exists categories_update on public.meeting_categories;
create policy categories_update on public.meeting_categories
  for update to authenticated
  using (public.may('category.manage', municipality_id))
  with check (public.may('category.manage', municipality_id));

drop policy if exists categories_delete on public.meeting_categories;
create policy categories_delete on public.meeting_categories
  for delete to authenticated
  using (public.may('category.delete', municipality_id));

-- ---------------------------------------------------------------------
-- meetings
--
-- Drafts are invisible to anon. On update, WITH CHECK inspects the row as
-- it will exist after the write, so an editor without meeting.publish can
-- never leave a row in the published state - including by editing one that
-- is already published.
-- ---------------------------------------------------------------------
drop policy if exists meetings_public_read on public.meetings;
create policy meetings_public_read on public.meetings
  for select to anon
  using (
    status in ('published', 'archived')
    and exists (select 1 from public.municipalities m
                where m.id = municipality_id and m.active)
  );

drop policy if exists meetings_member_read on public.meetings;
create policy meetings_member_read on public.meetings
  for select to authenticated
  using (public.may('meeting.read', municipality_id));

drop policy if exists meetings_insert on public.meetings;
create policy meetings_insert on public.meetings
  for insert to authenticated
  with check (
    public.may('meeting.create', municipality_id)
    and (status <> 'published' or public.has_permission('meeting.publish'))
    and (status <> 'archived'  or public.has_permission('meeting.archive'))
  );

drop policy if exists meetings_update on public.meetings;
create policy meetings_update on public.meetings
  for update to authenticated
  using (public.may('meeting.update', municipality_id))
  with check (
    public.may('meeting.update', municipality_id)
    and (status <> 'published' or public.has_permission('meeting.publish'))
    and (status <> 'archived'  or public.has_permission('meeting.archive'))
  );

drop policy if exists meetings_delete on public.meetings;
create policy meetings_delete on public.meetings
  for delete to authenticated
  using (public.may('meeting.delete', municipality_id));

-- ---------------------------------------------------------------------
-- meeting_documents
-- ---------------------------------------------------------------------
drop policy if exists documents_public_read on public.meeting_documents;
create policy documents_public_read on public.meeting_documents
  for select to anon
  using (
    active_version
    and removed_at is null
    and exists (
      select 1
      from public.meetings mt
      join public.municipalities mu on mu.id = mt.municipality_id
      where mt.id = meeting_id
        and mu.active
        and mt.status in ('published', 'archived')
        and (document_type <> 'minutes'
             or public.minutes_publicly_visible(mt.minutes_status, mu.configuration))
    )
  );

drop policy if exists documents_member_read on public.meeting_documents;
create policy documents_member_read on public.meeting_documents
  for select to authenticated
  using (public.may('document.read', municipality_id));

drop policy if exists documents_insert on public.meeting_documents;
create policy documents_insert on public.meeting_documents
  for insert to authenticated
  with check (public.may('document.manage', municipality_id));

drop policy if exists documents_update on public.meeting_documents;
create policy documents_update on public.meeting_documents
  for update to authenticated
  using (public.may('document.manage', municipality_id))
  with check (public.may('document.manage', municipality_id));

drop policy if exists documents_delete on public.meeting_documents;
create policy documents_delete on public.meeting_documents
  for delete to authenticated
  using (public.may('document.delete', municipality_id));

-- ---------------------------------------------------------------------
-- audit_log - readable by permitted staff, writable by nobody.
-- Rows are inserted by public.record_audit_event(), which is SECURITY
-- DEFINER and owned by the table owner, so it bypasses these policies.
-- ---------------------------------------------------------------------
drop policy if exists audit_read on public.audit_log;
create policy audit_read on public.audit_log
  for select to authenticated
  using (public.may('audit.read', municipality_id));

-- # END 20260101000400_rls_policies.sql

-- #####################################################################
-- # BEGIN 20260101000500_storage.sql
-- #####################################################################

-- =====================================================================
-- 0500 - Supabase Storage
--
-- The bucket is private. Nothing in it is ever served directly to the
-- public; citizens reach documents through /documents/... which checks
-- publication state first and then streams the object server side.
-- =====================================================================

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'meeting-documents',
  'meeting-documents',
  false,
  52428800,                      -- 50 MB ceiling; the app enforces a lower,
  array['application/pdf']       -- configurable limit per municipality.
)
on conflict (id) do update
  set public = excluded.public,
      file_size_limit = excluded.file_size_limit,
      allowed_mime_types = excluded.allowed_mime_types;

-- Path shape: municipalities/{municipality_id}/meetings/{meeting_id}/{type}/{file}
create or replace function public.object_municipality_id(object_name text)
returns uuid language plpgsql immutable as $$
declare parts text[] := string_to_array(object_name, '/');
begin
  if array_length(parts, 1) < 2 or parts[1] <> 'municipalities' then
    return null;
  end if;
  return parts[2]::uuid;
exception when others then return null;
end;
$$;

drop policy if exists "staff read own municipality documents" on storage.objects;
create policy "staff read own municipality documents"
  on storage.objects for select to authenticated
  using (
    bucket_id = 'meeting-documents'
    and public.may('document.read', public.object_municipality_id(name))
  );

drop policy if exists "staff write own municipality documents" on storage.objects;
create policy "staff write own municipality documents"
  on storage.objects for insert to authenticated
  with check (
    bucket_id = 'meeting-documents'
    and public.may('document.manage', public.object_municipality_id(name))
  );

drop policy if exists "staff update own municipality documents" on storage.objects;
create policy "staff update own municipality documents"
  on storage.objects for update to authenticated
  using (
    bucket_id = 'meeting-documents'
    and public.may('document.manage', public.object_municipality_id(name))
  );

-- Superseded versions are retained. Only a role holding document.delete may
-- remove bytes, and only inside its own tenant folder.
drop policy if exists "restricted delete of municipality documents" on storage.objects;
create policy "restricted delete of municipality documents"
  on storage.objects for delete to authenticated
  using (
    bucket_id = 'meeting-documents'
    and public.may('document.delete', public.object_municipality_id(name))
  );

-- Deliberately absent: any policy granting the `anon` role access to
-- storage.objects. Public document delivery goes through the application.

-- # END 20260101000500_storage.sql

-- #####################################################################
-- # BEGIN 20260101000600_reference_data.sql
-- #####################################################################

-- =====================================================================
-- 0600 - Reference data
--
-- This is schema, not sample content: the permission matrix and the
-- document type list are part of the security model and must be
-- reproducible from migrations alone.
-- =====================================================================

insert into public.document_types (code, label, display_order) values
  ('agenda',  'Agenda',  10),
  ('minutes', 'Minutes', 20)
on conflict (code) do update set label = excluded.label,
                                 display_order = excluded.display_order;

-- Super administrators are not listed: public.has_permission() grants them
-- everything unconditionally.
delete from public.role_permissions where role <> 'super_admin';

insert into public.role_permissions (role, permission) values
  -- Administrator: everything inside their own municipality.
  ('admin', 'meeting.read'),
  ('admin', 'meeting.create'),
  ('admin', 'meeting.update'),
  ('admin', 'meeting.publish'),
  ('admin', 'meeting.archive'),
  ('admin', 'meeting.delete'),
  ('admin', 'document.read'),
  ('admin', 'document.manage'),
  ('admin', 'document.delete'),
  ('admin', 'category.read'),
  ('admin', 'category.manage'),
  ('admin', 'category.delete'),
  ('admin', 'user.read'),
  ('admin', 'user.manage'),
  ('admin', 'audit.read'),
  ('admin', 'municipality.update'),

  -- Editor / City Secretary: the day to day clerk workflow.
  ('editor', 'meeting.read'),
  ('editor', 'meeting.create'),
  ('editor', 'meeting.update'),
  ('editor', 'meeting.publish'),
  ('editor', 'document.read'),
  ('editor', 'document.manage'),
  ('editor', 'category.read'),
  ('editor', 'audit.read'),

  -- Read only: look, do not touch.
  ('read_only', 'meeting.read'),
  ('read_only', 'document.read'),
  ('read_only', 'category.read'),
  ('read_only', 'audit.read')
on conflict do nothing;

-- ---------------------------------------------------------------------
-- Convenience view for the admin dashboard counters.
-- ---------------------------------------------------------------------
create or replace view public.meeting_dashboard_counts
with (security_invoker = true) as
select
  m.municipality_id,
  count(*) filter (where m.status = 'published' and m.starts_at >= now())            as upcoming,
  count(*) filter (where m.status = 'draft')                                          as drafts,
  count(*) filter (where m.status = 'published')                                      as published,
  count(*) filter (where m.status = 'archived')                                       as archived,
  count(*) filter (where m.status = 'published' and m.starts_at < now()
                     and m.minutes_status = 'not_available')                          as awaiting_minutes,
  count(*) filter (where m.minutes_status = 'pending_approval')                       as minutes_pending_approval,
  count(*) filter (where m.status = 'published'
                     and date_part('year', m.starts_at) = date_part('year', now()))   as published_this_year
from public.meetings m
group by m.municipality_id;

grant select on public.meeting_dashboard_counts to authenticated;

-- # END 20260101000600_reference_data.sql

-- #####################################################################
-- # BEGIN 20260101000700_operations.sql
-- #####################################################################

-- =====================================================================
-- 0700 - Multi-statement operations that must not half-happen
--
-- These run SECURITY INVOKER, so Row-Level Security still applies to every
-- statement inside them. They exist for atomicity, not for privilege.
-- =====================================================================

-- ---------------------------------------------------------------------
-- Upload or replace a document.
--
-- Version 1 is an upload. Every later version supersedes the previous one
-- and inherits its public_slug, so the URL already printed on a public
-- notice keeps resolving to the current record. The superseded row is
-- retained: previous government documents are never destroyed here.
-- ---------------------------------------------------------------------
create or replace function public.upsert_meeting_document(
  p_meeting_id        uuid,
  p_document_type     text,
  p_posted_date       date,
  p_storage_path      text,
  p_original_filename text,
  p_stored_filename   text,
  p_file_size         bigint,
  p_sha256            text default null
) returns public.meeting_documents
language plpgsql
set search_path = public, pg_temp
as $$
declare
  v_meeting  public.meetings;
  v_current  public.meeting_documents;
  v_profile  public.profiles;
  v_version  integer := 1;
  v_slug     text;
  v_row      public.meeting_documents;
begin
  select * into v_meeting from public.meetings where id = p_meeting_id;
  if not found then
    raise exception 'That meeting could not be found.' using errcode = 'P0002';
  end if;

  if p_posted_date is null then
    raise exception 'A Posted Date is required whenever a document is uploaded.'
      using errcode = '23502';
  end if;

  v_profile := public.current_profile();

  select * into v_current
  from public.meeting_documents
  where meeting_id = p_meeting_id
    and document_type = p_document_type
    and active_version;

  if found then
    v_version := v_current.version + 1;
    v_slug    := v_current.public_slug;

    update public.meeting_documents
       set active_version = false,
           replaced_at = now()
     where id = v_current.id;
  else
    -- New public identifier, derived from the meeting so it reads clearly in
    -- an email or on a QR code, with a numeric suffix only if it collides.
    v_slug := v_meeting.meeting_date || '-' || v_meeting.slug || '-' || p_document_type;
    if exists (
      select 1 from public.meeting_documents
      where municipality_id = v_meeting.municipality_id
        and public_slug = v_slug
        and active_version
    ) then
      v_slug := v_slug || '-' || substr(replace(gen_random_uuid()::text, '-', ''), 1, 6);
    end if;
  end if;

  insert into public.meeting_documents (
    municipality_id, meeting_id, document_type, posted_date, storage_path,
    public_slug, original_filename, stored_filename, mime_type, file_size,
    sha256, version, active_version, uploaded_by)
  values (
    v_meeting.municipality_id, p_meeting_id, p_document_type, p_posted_date,
    p_storage_path, v_slug, p_original_filename, p_stored_filename,
    'application/pdf', p_file_size, p_sha256, v_version, true, v_profile.id)
  returning * into v_row;

  return v_row;
end;
$$;

grant execute on function public.upsert_meeting_document(uuid, text, date, text, text, text, bigint, text)
  to authenticated;

-- ---------------------------------------------------------------------
-- Duplicate a meeting.
--
-- Copies the recurring details a clerk would retype. Deliberately does not
-- copy documents, posted dates, approval status, or history: the new record
-- starts as an empty draft that happens to be pre-filled.
-- ---------------------------------------------------------------------
create or replace function public.duplicate_meeting(
  p_meeting_id       uuid,
  p_meeting_date     date,
  p_copy_description boolean default true
) returns public.meetings
language plpgsql
set search_path = public, pg_temp
as $$
declare
  v_source public.meetings;
  v_new    public.meetings;
  v_profile public.profiles;
begin
  select * into v_source from public.meetings where id = p_meeting_id;
  if not found then
    raise exception 'That meeting could not be found.' using errcode = 'P0002';
  end if;

  v_profile := public.current_profile();

  insert into public.meetings (
    municipality_id, category_id, title, slug, description, meeting_date,
    meeting_time, location, status, minutes_status, created_by, updated_by)
  values (
    v_source.municipality_id, v_source.category_id, v_source.title, v_source.slug,
    case when p_copy_description then v_source.description else null end,
    p_meeting_date, v_source.meeting_time, v_source.location,
    'draft', 'not_available', v_profile.id, v_profile.id)
  returning * into v_new;

  perform public.record_audit_event(
    v_new.municipality_id, 'meeting.duplicated', 'meeting', v_new.id::text,
    null, to_jsonb(v_new), jsonb_build_object('duplicated_from', p_meeting_id));

  return v_new;
end;
$$;

grant execute on function public.duplicate_meeting(uuid, date, boolean) to authenticated;

-- ---------------------------------------------------------------------
-- Remove a document from public view without destroying it.
-- ---------------------------------------------------------------------
create or replace function public.retire_meeting_document(p_document_id uuid)
returns public.meeting_documents
language plpgsql
set search_path = public, pg_temp
as $$
declare v_row public.meeting_documents;
begin
  update public.meeting_documents
     set active_version = false,
         removed_at = now(),
         replaced_at = coalesce(replaced_at, now())
   where id = p_document_id
   returning * into v_row;

  if not found then
    raise exception 'That document could not be found.' using errcode = 'P0002';
  end if;

  return v_row;
end;
$$;

grant execute on function public.retire_meeting_document(uuid) to authenticated;

-- # END 20260101000700_operations.sql

-- #####################################################################
-- # BEGIN 20260101000800_schema_version.sql
-- #####################################################################

-- =====================================================================
-- 0800 - Schema version
--
-- Records which release created or last updated this database.
--
-- The Supabase CLI keeps its own migration ledger, but a database
-- installed from the dashboard (supabase/setup/01-complete-schema.sql)
-- has no ledger at all. Without this, nobody can answer "which version
-- is this project running?" without reading the schema by hand — which
-- is exactly the question asked when something behaves unexpectedly
-- after an update.
--
-- Bump the value below in the same commit as any schema change.
-- =====================================================================

create table if not exists public.schema_version (
  version     text primary key,
  applied_at  timestamptz not null default now(),
  notes       text
);

comment on table public.schema_version is
  'One row per release whose migrations have been applied. Newest row is current.';

alter table public.schema_version enable row level security;

-- Staff may read it; the public has no reason to know the version, and
-- advertising it to anonymous callers only helps someone fingerprinting
-- the deployment.
drop policy if exists schema_version_read on public.schema_version;
create policy schema_version_read on public.schema_version
  for select to authenticated
  using (true);

-- No insert, update, or delete policy: only a migration, running with
-- elevated privileges, writes here.

insert into public.schema_version (version, notes)
values ('1.2.0', 'Adds schema version tracking and idempotent policies/triggers.')
on conflict (version) do update
  set applied_at = now(),
      notes = excluded.notes;

-- # END 20260101000800_schema_version.sql

-- =====================================================================
-- Done. Verify with the queries in docs/WEB-SETUP.md, Step 5.
-- =====================================================================
